apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cloudflared
  name: cloudflared
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-secret: "selfsigned-cert-tls"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        vault.hashicorp.com/role: "cloudflared"
        vault.hashicorp.com/agent-inject-secret-credentials.json: 'kv/data/infra/network/cloudflared/tunnel_creds'
        vault.hashicorp.com/agent-inject-template-credentials.json: |
          {{- with secret "kv/data/infra/network/cloudflared/tunnel_creds" -}}
          {{ .Data.data.creds }}
          {{- end -}}
    spec:
      serviceAccountName: cloudflared
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          imagePullPolicy: IfNotPresent
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 60
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config/config.yaml
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: config