apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-ip-pool
spec:
  blocks:
    - cidr: "10.20.0.0/24"
  serviceSelector:
    matchLabels:
      bgp.cilium.io/ip-pool: default
