apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: dragonfly-operator-vpa
  namespace: dragonfly-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       dragonfly-operator
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 250m
        memory: 256Mi
      maxAllowed:
        cpu: 2000m
        memory: 2048Mi
      controlledResources: ["cpu", "memory"]