apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: network
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/sud0ce0/homelab-apps.git"
  destinations:
    - namespace: "argocd"
      server: "*"
    - namespace: "kube-system"
      server: "*"
    - namespace: "cilium-secrets"
      server: "*"
    - namespace: "cloudflared"
      server: "*"
    - namespace: "traefik-internal"
      server: "*"
    - namespace: "traefik-external"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
