apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: argocd-auth
  namespace: argocd
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: argocd
    serviceAccount: argocd-server
    audiences:
      - vault