apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argocd-reposerver-vpa
  namespace: argocd
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       argocd-repo-server
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 100m
        memory: 256Mi
      maxAllowed:
        cpu: 2000m
        memory: 4096Mi
      controlledResources: ["cpu", "memory"]