apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: authentik
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: authentik
    serviceAccount: authentik
    audiences:
      - vault