crds:
  enabled: true
  keep: true
extraArgs:
  - "--enable-gateway-api"

serviceAccount:
  create: true
  name: cert-manager

resources: {}
webhook:
  resources: {}
cainjector:
  resources: {}

prometheus:
  enabled: true
  servicemonitor:
    enabled: true